kind: ConfigMap
apiVersion: v1
metadata:
  name: svc-bgp-config 
  namespace: kube-system
data:
  exabgp.conf: |
      process svc-bgp {
        run /usr/bin/python -u /opt/k8s-bgp.py;
        encoder text;
      }
      neighbor 77.80.231.241 {
        router-id __POD_IP__;
        local-address __POD_IP__;
        local-as 65001;
        peer-as 65000;
        family {
          ipv4 unicast;
        }
       api {
         processes [ svc-bgp ];
       }
      }

  start-exabgp.sh: |
      #!/bin/bash
      echo "77.80.231.33 kubernetes.default" >> /etc/hosts
      /bin/sed -i s/__POD_IP__/${POD_IP}/g /etc/exabgp/exabgp.conf
      /usr/bin/env \
        exabgp.log.routes=true \
        exabgp.daemon.user=root \
        exabgp /etc/exabgp/exabgp.conf

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: svc-bgp
  namespace: kube-system
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name: svc-bgp
      labels:
        app: svc-bgp
    spec:
      containers:
      - image: svc-bgp
        imagePullPolicy: Never
        name: svc-bgp
        securityContext:
          privileged: true
        volumeMounts:
        - name: config-volume
          mountPath: /etc/exabgp
        env:
        - name: SVC_BGP_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        command: ["/bin/bash", "/etc/exabgp/start-exabgp.sh"]
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
       - name: config-volume
         configMap:
           name: svc-bgp-config

---

