apiVersion: v1
kind: Service
metadata:
  labels:
    app: snmpexporterd
  name: prober
  namespace: prod
spec:
  clusterIP: 77.80.229.134
  ports:
  - name: probe
    port: 80
    protocol: TCP
    targetPort: 9190
  selector:
    app: snmpexporterd
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: snmpexporterd
  name: snmpexporterd
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snmpexporterd
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: snmpexporterd
      name: snmpexporterd
    spec:
      containers:
      - image: val.tech.dreamhack.se/snmpexporterd
        imagePullPolicy: Always
        name: snmpexporterd
        volumeMounts:
          - name: config-volume
            mountPath: /etc/snmpexporter
        resources:
              requests:
                memory: "1Gi"
              limits:
                memory: "1.2Gi"
        livenessProbe:
          httpGet:
            path: /healthy
            port: 9190
          initialDelaySeconds: 15
          timeoutSeconds: 30
      imagePullSecrets:
      - name: tech-registry-key
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: config-volume
          configMap:
            name: snmpexporter
