apiVersion: v1
kind: Service
metadata:
  labels:
    app: ldap
  name: ldap
  namespace: ldap
spec:
  ports:
  - name: ldap
    port: 636
    protocol: TCP
    targetPort: 636
    nodePort: 30018
  selector:
    app: ldap
  sessionAffinity: None
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: ldap
  name: ldap
  namespace: ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ldap
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ldap
      name: ldap
    spec:
      containers:
      - image: quay.io/dhtech/ldap
        imagePullPolicy: Always
        name: ldap
        volumeMounts:
          - name: tls-volume
            mountPath: /etc/ssl/ldap
        resources:
              requests:
                memory: "500Mi"
              limits:
                memory: "900Mi"
        readinessProbe:
          exec:
            command:
              - /ready.sh
        livenessProbe:
          exec:
            command:
              - ldapsearch -x -H ldapi:/// -s base -LLL dc
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: tls-volume
          secret:
            secretName: ldap-tls
