apiVersion: v1
kind: Service
metadata:
  name: heapster
  namespace: kube-system
spec:
  clusterIP: 77.80.231.60
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8082
  selector:
    k8s-app: heapster
  sessionAffinity: None
  type: ClusterIP
